# Site settings
title: Conor McAfee
email: hello@conormcafee.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Designer & Front-End Developer from Ballymena, Northern Ireland.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://conormcafee.github.io" # the base hostname & protocol for your site
twitter_username: conormcafee
github_username:  conormcafee

# Build settings
markdown: kramdown
