# Site settings
title: Conor McAfee
email: hello@conormcafee.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Conor McAfee is a Designer & Front-End Developer from Ballymena, Northern Ireland.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://conormcafee.co.uk # the base hostname & protocol for your site
twitter_username: conormcafee
github_username:  conormcafee

# Build settings
markdown: kramdown
permalink: /:categories/:title.html
sass:
    style: compressed
exclude: [node_modules]
